name: Fetch Stock Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day. Adjust as necessary.
  workflow_dispatch:  # This line enables manual triggering.

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jugaad_data

      - name: Fetch and Save Data
        run: python fetch_data.py

      - name: Upload Log File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: log-files
          path: fetch_data.log

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "anujshah584@gmail.com"
          git config --global user.name "Anuj Shah"
          git add -A
          git commit -m "Updated data" -a || echo "No changes to commit"
          git push
